version: '3.9'

services:
  proxy:
    build:
      dockerfile: Dockerfile
      context: .
    image: eben0/modsecurity-nginx-proxy
    ports:
      - 80:80
      - 443:443
    container_name: proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./modsecurity.d/rules:/etc/modsecurity.d/rules:ro
      - nginx-certs:/etc/nginx/certs
      - nginx-vhost:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html
    environment:
      MODSEC_DEBUG_LOGLEVEL: 5
    networks:
      service_network:

  web:
    image: nginx
    container_name: web
    environment:
      VIRTUAL_PORT: 8080
      VIRTUAL_HOST: web.example.com
    networks:
      service_network:

networks:
  service_network:

volumes:
  nginx-certs:
  nginx-vhost:
  nginx-html: